// THE VERDICT SPINE: the part of a screenshot run that belongs in git.
//
// A run produces three things. Two of them are evidence and one of them is
// working-out:
//
//   PNGs          the pictures. Regenerated by every sweep, ~10 MiB a run,
//                 gitignored since wave 1.
//   manifest.json every figure, every pixel sample, every occluder pair, every
//                 token the census classified. It went from 763,703 bytes to
//                 7,612,380 in ONE wave when per-figure pixel sampling arrived,
//                 and `make hygiene` went red on it (docs/DEFECTS.md E-60). No
//                 human has ever read it. It is build output.
//   INDEX.md      the human-readable table.
//
// What was missing is a MACHINE-readable form of the verdicts that is small
// enough to live in git for ever. That is this file's output: one row per
// (scene, viewport), its verdict, and the headline of each thing that failed --
// no pixel samples, no token lists, no per-figure geometry.
//
// It exists for two reasons, and the second is the important one:
//
//   1. it is the evidence trail after the manifest stops being tracked; and
//   2. `./scripts/dev.sh shots-verdict` gates on it, so a RED recorded by the
//      last sweep keeps failing a cheap gate until somebody writes it down --
//      including in a wave that cannot run the sweep at all. The occlusion
//      regression in E-61's wave sat in an artifact, unacknowledged, through a
//      whole wave, because nothing but the sweep itself could see it and the
//      sweep could not run.

/** Longest failure headline kept. Enough to identify it; the manifest has the rest. */
const MAX_PROBLEM_CHARS = 400;

/** Most headlines kept per shot. */
const MAX_PROBLEMS = 12;

const clip = (s) => {
    const t = String(s).replace(/\s+/g, ' ').trim();
    return t.length > MAX_PROBLEM_CHARS ? `${t.slice(0, MAX_PROBLEM_CHARS - 1)}…` : t;
};

/**
 * Every reason this shot is not verified, as short headlines.
 *
 * The notes string a scene writes is already the concatenation the INDEX table
 * renders, and it is where the harness puts `OCCLUSION FAILED`, `TOKEN CENSUS
 * FAILED`, `RAKE TAKEN` and the chain disagreements. Splitting it on its own
 * separators is what keeps this file independent of the shape of `checks`, which
 * is the part that grows 10x a wave.
 *
 * @param {object} shot
 * @returns {string[]}
 */
function problemsOf(shot) {
    if (shot.error) return [clip(shot.error)];
    const notes = String(shot.notes || '');
    // ` || ` separates the failure clauses from each other and from the scene's
    // descriptive notes; the INDEX table renders the same string with ` // `.
    const clauses = notes.split(/\s+\|\|\s+|\s+\/\/\s+/).map((c) => c.trim()).filter(Boolean);
    // THE VOCABULARY IS PART OF THE GATE, AND IT WAS SHORT BY TWO WHOLE CHECKS.
    //
    // docs/DEFECTS.md E-88. When at least one clause matches, the rest are
    // DROPPED, so a failure phrased in words this pattern does not know is not
    // just unrecognised -- it is deleted from the tracked verdict and can never be
    // acknowledged. Neither the felt-area floor ("below the 45% floor") nor
    // `table-in-frame.mjs` ("is NOT fully inside the 1440x900 frame") used any of
    // the original six words. They survived only because they happened to be the
    // ONLY clauses on their shots, so the `clauses` fallback fired; the first shot
    // to fail an occlusion check AND the felt floor would have recorded the
    // occlusion and silently lost the felt. Every phrase a check can emit belongs
    // here, and a new check must add its own.
    const failures = clauses.filter((c) => new RegExp(
        [
            'FAILED', 'DISAGREE', 'RAKE TAKEN', 'STRUCTURAL', 'MISSING', 'COVERED',
            'below the \\d',        // lib/felt-area.mjs, the playing-surface floor
            'NOT fully inside',     // lib/table-in-frame.mjs, anything off frame
            'OFF FRAME',
            'no pot readout',       // lib/table-in-frame.mjs, an empty required set
            'no seat ring',
            'paint nothing',
            // NOT `unaccounted for`: the token census prints "0 unaccounted for" in
            // its HEALTHY note, so that phrase classifies a scene's descriptive
            // clause as a failure and drags it into the tracked verdict. The census
            // says `TOKEN CENSUS FAILED` when it actually fails, which `FAILED`
            // already covers. A marker that matches a passing message is the same
            // defect as a marker that misses a failing one, pointed the other way.
        ].join('|'), 'i',
    ).test(c));
    const kept = (failures.length ? failures : clauses).slice(0, MAX_PROBLEMS);
    return kept.map(clip);
}

/**
 * The small, tracked projection of a run.
 *
 * @param {object} manifest the full in-memory manifest
 * @returns {object}
 */
export function buildVerdicts(manifest) {
    const shots = [];
    for (const scene of manifest.scenes || []) {
        for (const shot of scene.shots || []) {
            // The FILENAME is the single source of truth for a shot's verdict:
            // only a verified shot is allowed the canonical name (run.mjs writes
            // `UNVERIFIED-*` / `FAILED-*` otherwise), and per-shot is the right
            // grain -- `deposit` verifies at desktop and cannot at mobile.
            const file = (shot.files?.[0] || '').split('/').pop() || '';
            const verified = Boolean(file) && !file.startsWith('UNVERIFIED-') && !file.startsWith('FAILED-');
            shots.push({
                scene: scene.scene,
                viewport: shot.viewport,
                verified,
                file,
                problems: verified ? [] : problemsOf(shot),
            });
        }
    }
    return {
        // Provenance, so a reader can tell whether this verdict describes the
        // tree they are looking at.
        gitSha: manifest.gitSha,
        gitDirty: manifest.gitDirty,
        startedAt: manifest.startedAt,
        finishedAt: manifest.finishedAt,
        faultInjection: manifest.faultInjection ? manifest.faultInjection.targets : null,
        // Where the working-out went. It is NOT in git.
        fullManifest: 'manifest.json in this directory -- gitignored build output, '
            + 'regenerated by `./scripts/dev.sh shots`',
        counts: {
            shots: shots.length,
            verified: shots.filter((s) => s.verified).length,
            red: shots.filter((s) => !s.verified).length,
        },
        shots,
    };
}
