//! BEHAVIOUR LOCK for the ClearDeck poker engine.
//!
//! `golden_vectors.txt` was generated by running the ORIGINAL engine, textually
//! extracted from `git show ceacc37:src/table_canister/src/lib.rs`, BEFORE the
//! `poker_core` refactor. Every vector in it must be reproduced exactly by the
//! refactored crate. A failure here means the refactor changed observable
//! behaviour of a canister that custodies real ICP/ckBTC.
//!
//! Why each family matters:
//!
//! * `S` -- `shuffle_deck`. The revealed seed plus this function IS the fairness
//!   proof players verify. Changing it retroactively invalidates every hand ever
//!   dealt. 2,000 seeds of varying length.
//! * `E` / `F` -- `evaluate_hand` / `evaluate_five_cards`. Decides who takes the
//!   money. 3,000 random 7-card and 3,000 random 5-card boards.
//! * `D` -- `detect_straight` / `check_straight` / `get_straight_high`, EXHAUSTIVE
//!   over all 6,188 five-card rank multisets, so wheel handling is fully pinned.
//! * `P` -- side-pot construction through the same entry point the canister uses,
//!   `apply_side_pots`, with the side-pot list pre-seeded so the "nobody bet, so
//!   leave the previous pots alone" early return is pinned too. 1,500 cases,
//!   including saturating `u64::MAX` bets and 466 cases that trip the
//!   proportional-capping branch.
//!
//! Regenerating these vectors is a deliberate act, never a convenience. If a
//! change here is intended, it is a change in payout behaviour and needs a
//! written justification.
//!
//! # How the fixture was produced, and how to reproduce it
//!
//! The generator is a throwaway host binary that `include!`s the ORIGINAL code
//! rather than a retyped copy of it, so nothing can drift in transcription:
//!
//! ```text
//! git show ceacc37:src/table_canister/src/lib.rs > orig_lib.rs
//!
//! # Assemble a generator module from orig_lib.rs. Two textual edits only:
//! #   * derive lists lose `CandidType, Deserialize, `  (no candid dep needed)
//! #   * `ic_cdk::println!` becomes a macro that pushes into a Vec<String>
//! # plus minimal stand-ins for the three TableState fields calculate_side_pots
//! # touches (players: Vec<Option<Player>>, side_pots, pot).
//! # `include!` it into main.rs so the private `fn`s stay reachable -- NO
//! # visibility edits.
//!
//! cargo run --release > golden_vectors.txt
//! ```
//!
//! The generator drives, per family: `shuffle_deck` over 2,000 derived seeds;
//! `evaluate_hand` and `evaluate_five_cards` over SplitMix64-chosen card sets with
//! fixed seeds; `detect_straight` exhaustively; and the ORIGINAL
//! `calculate_side_pots(&mut TableState)` over 1,500 randomised tables whose
//! `pot` is deliberately set to sum, sum/2, sum*2, 0 and `u64::MAX` so both
//! reconciliation branches are reached.
//!
//! The suite was mutation-checked: perturbing the shuffle modulus, the capping
//! ratio, or `create_deck`'s suit order each turns it red.

use poker_core::{
    apply_side_pots, check_straight, create_deck, detect_straight, evaluate_five_cards,
    evaluate_hand, get_straight_high, shuffle_deck, Card, Contribution, Rank, SidePot, Suit,
};

const GOLDEN: &str = include_str!("golden_vectors.txt");
const ALPHA: &[u8] = b"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz";

const SUITS: [Suit; 4] = [Suit::Hearts, Suit::Diamonds, Suit::Clubs, Suit::Spades];
const RANKS: [Rank; 13] = [
    Rank::Two,
    Rank::Three,
    Rank::Four,
    Rank::Five,
    Rank::Six,
    Rank::Seven,
    Rank::Eight,
    Rank::Nine,
    Rank::Ten,
    Rank::Jack,
    Rank::Queen,
    Rank::King,
    Rank::Ace,
];

/// Cards are encoded ABSOLUTELY: suit ordinal (H,D,C,S) * 13 + (rank - 2).
///
/// Deliberately NOT "position in `create_deck()`". An encoding relative to
/// `create_deck()` cancels out on both sides, so reordering the deck would slip
/// past every vector -- verified by mutation testing. `create_deck`'s own order is
/// pinned separately by `create_deck_order_is_pinned`.
fn card_from_index(idx: usize) -> Card {
    Card {
        suit: SUITS[idx / 13],
        rank: RANKS[idx % 13],
    }
}

fn card_index(c: &Card) -> usize {
    let suit_ord = match c.suit {
        Suit::Hearts => 0usize,
        Suit::Diamonds => 1,
        Suit::Clubs => 2,
        Suit::Spades => 3,
    };
    suit_ord * 13 + (c.rank.value() as usize - 2)
}

fn decode_cards(symbols: &str) -> Vec<Card> {
    symbols
        .bytes()
        .map(|b| {
            let idx = ALPHA
                .iter()
                .position(|&a| a == b)
                .unwrap_or_else(|| panic!("bad card symbol {:?}", b as char));
            card_from_index(idx)
        })
        .collect()
}

fn encode_cards(cards: &[Card]) -> String {
    cards
        .iter()
        .map(|c| ALPHA[card_index(c)] as char)
        .collect()
}

fn decode_hex(s: &str) -> Vec<u8> {
    assert!(s.len() % 2 == 0, "odd-length hex: {}", s);
    (0..s.len())
        .step_by(2)
        .map(|i| u8::from_str_radix(&s[i..i + 2], 16).expect("bad hex"))
        .collect()
}

/// Must match the generator's encoding exactly.
fn encode_pots(pots: &[SidePot]) -> String {
    if pots.is_empty() {
        return "-".to_string();
    }
    pots.iter()
        .map(|p| {
            let elig: Vec<String> = p.eligible_players.iter().map(|s| s.to_string()).collect();
            format!("{}#{}", p.amount, elig.join(","))
        })
        .collect::<Vec<_>>()
        .join(";")
}

fn parse_contributions(field: &str) -> Vec<Contribution> {
    if field == "-" {
        return Vec::new();
    }
    field
        .split(';')
        .map(|entry| {
            let mut it = entry.split(':');
            let seat: u8 = it.next().expect("seat").parse().expect("seat");
            let bet: u64 = it.next().expect("bet").parse().expect("bet");
            let folded: u8 = it.next().expect("folded").parse().expect("folded");
            Contribution::new(seat, bet, folded == 1)
        })
        .collect()
}

/// Exactly what `table_canister::calculate_side_pots` does, minus the logging.
/// The generator drove the ORIGINAL `calculate_side_pots(&mut TableState)` with
/// the same pre-seeded sentinel, so this pins the adapter contract as well as the
/// arithmetic.
fn replay_side_pots(
    contributions: &[Contribution],
    total_pot: u64,
) -> (Vec<SidePot>, Vec<String>) {
    let mut pots = vec![SidePot {
        amount: 999,
        eligible_players: vec![7],
    }];
    // The original routine dropped players who bet nothing while collecting, so
    // an all-zero table yields no contributions and the early return applies.
    let live: Vec<Contribution> = contributions
        .iter()
        .filter(|c| c.total_bet_this_hand > 0)
        .copied()
        .collect();
    let warnings = apply_side_pots(&mut pots, &live, total_pot);
    (pots, warnings)
}

struct Counts {
    shuffle: usize,
    seven_card: usize,
    five_card: usize,
    straight: usize,
    side_pots: usize,
}

fn run_all() -> Counts {
    let mut counts = Counts {
        shuffle: 0,
        seven_card: 0,
        five_card: 0,
        straight: 0,
        side_pots: 0,
    };

    for (lineno, line) in GOLDEN.lines().enumerate() {
        let lineno = lineno + 1;
        if line.is_empty() || line.starts_with('#') {
            continue;
        }
        let kind = &line[..1];
        let rest = &line[2..];

        match kind {
            "S" => {
                let mut it = rest.splitn(2, ' ');
                let seed = decode_hex(it.next().expect("seed"));
                let expected = it.next().expect("deck");
                let mut deck = create_deck();
                shuffle_deck(&mut deck, &seed);
                assert_eq!(
                    encode_cards(&deck),
                    expected,
                    "shuffle_deck diverged from the pre-refactor engine at line {}",
                    lineno
                );
                counts.shuffle += 1;
            }
            "E" => {
                let mut it = rest.splitn(2, ' ');
                let cards = decode_cards(it.next().expect("cards"));
                let expected = it.next().expect("rank");
                assert_eq!(cards.len(), 7, "line {}", lineno);
                let hole = (cards[0], cards[1]);
                let got = evaluate_hand(&hole, &cards[2..7]);
                assert_eq!(
                    format!("{:?}", got),
                    expected,
                    "evaluate_hand diverged from the pre-refactor engine at line {}",
                    lineno
                );
                counts.seven_card += 1;
            }
            "F" => {
                let mut it = rest.splitn(2, ' ');
                let cards = decode_cards(it.next().expect("cards"));
                let expected = it.next().expect("rank");
                assert_eq!(cards.len(), 5, "line {}", lineno);
                let got = evaluate_five_cards(&cards);
                assert_eq!(
                    format!("{:?}", got),
                    expected,
                    "evaluate_five_cards diverged from the pre-refactor engine at line {}",
                    lineno
                );
                counts.five_card += 1;
            }
            "D" => {
                let f: Vec<&str> = rest.split(' ').collect();
                assert_eq!(f.len(), 4, "line {}", lineno);
                let ranks: Vec<u8> = f[0].split(',').map(|r| r.parse().expect("rank")).collect();
                assert_eq!(
                    format!("{:?}", detect_straight(&ranks)),
                    f[1],
                    "detect_straight diverged at line {}",
                    lineno
                );
                assert_eq!(
                    check_straight(&ranks).to_string(),
                    f[2],
                    "check_straight diverged at line {}",
                    lineno
                );
                assert_eq!(
                    get_straight_high(&ranks).to_string(),
                    f[3],
                    "get_straight_high diverged at line {}",
                    lineno
                );
                counts.straight += 1;
            }
            "P" => {
                let f: Vec<&str> = rest.splitn(4, ' ').collect();
                assert_eq!(f.len(), 4, "line {}", lineno);
                let contributions = parse_contributions(f[0]);
                let total_pot: u64 = f[1].parse().expect("pot");
                let expected_pots = f[2];
                let expected_warnings = f[3];

                let (pots, warnings) = replay_side_pots(&contributions, total_pot);
                assert_eq!(
                    encode_pots(&pots),
                    expected_pots,
                    "side pots diverged from the pre-refactor engine at line {}\n  input: {}\n  pot:   {}",
                    lineno,
                    f[0],
                    total_pot
                );
                let warn_str = if warnings.is_empty() {
                    "-".to_string()
                } else {
                    warnings.join("~")
                };
                assert_eq!(
                    warn_str, expected_warnings,
                    "side-pot diagnostics diverged at line {}",
                    lineno
                );
                counts.side_pots += 1;
            }
            other => panic!("unknown vector kind {:?} at line {}", other, lineno),
        }
    }

    counts
}

#[test]
fn golden_vectors_reproduce_the_pre_refactor_engine() {
    let c = run_all();
    // Guard against a truncated or silently-emptied fixture.
    assert_eq!(c.shuffle, 2000, "expected 2000 shuffle vectors");
    assert_eq!(c.seven_card, 3000, "expected 3000 evaluate_hand vectors");
    assert_eq!(c.five_card, 3000, "expected 3000 evaluate_five_cards vectors");
    assert_eq!(
        c.straight, 6188,
        "expected all 6188 five-card rank multisets"
    );
    assert_eq!(c.side_pots, 1500, "expected 1500 side-pot vectors");
}

#[test]
fn create_deck_order_is_pinned() {
    // The pre-shuffle deck order is an input to the provably-fair shuffle, so it
    // is part of the fairness commitment: reordering it silently changes which
    // cards a given revealed seed deals. Every symbol, in order.
    assert_eq!(
        encode_cards(&create_deck()),
        std::str::from_utf8(ALPHA).unwrap(),
        "create_deck() no longer yields Hearts,Diamonds,Clubs,Spades x Two..Ace in order"
    );
    assert_eq!(create_deck().len(), 52);
}

#[test]
fn golden_side_pot_vectors_exercise_the_capping_branch() {
    // The f64 proportional-capping branch is the most dangerous code in the
    // side-pot routine, so assert the fixture really reaches it.
    let capped = GOLDEN
        .lines()
        .filter(|l| l.starts_with("P ") && l.contains("BUG: Side pots"))
        .count();
    assert!(
        capped >= 100,
        "golden fixture only reaches the capping branch {} times; it must stay covered",
        capped
    );
}
