//! BEHAVIOUR LOCK for the ClearDeck poker engine, replayed on the HOST.
//!
//! The checking logic lives in `tests/common/golden.rs` because the identical
//! vectors are also replayed on `wasm32-unknown-unknown` by `tests/wasm32_golden.rs`.
//! Green here plus green there is the claim; green here alone is not, and the
//! reason is `docs/FINDING-02-shuffle-not-verifiable.md`.
//!
//! Why each family matters:
//!
//! * `S` -- `shuffle_deck`. The revealed seed plus this function IS the fairness
//!   proof players verify. Changing it retroactively invalidates every hand ever
//!   dealt. 2,000 seeds of varying length.
//! * `E` / `F` -- `evaluate_hand` / `evaluate_five_cards`. Decides who takes the
//!   money. 3,000 random 7-card and 3,000 random 5-card boards.
//! * `D` -- `detect_straight` / `check_straight` / `get_straight_high`, EXHAUSTIVE
//!   over all 6,188 five-card rank multisets, so wheel handling is fully pinned.
//! * `P` -- side-pot construction through the same entry point the canister uses,
//!   `apply_side_pots`, with the side-pot list pre-seeded so the "nobody bet, so
//!   leave the previous pots alone" early return is pinned too. 1,500 cases,
//!   including saturating `u64::MAX` bets and 466 cases that trip the
//!   proportional-capping branch.
//!
//! Regenerating these vectors is a deliberate act, never a convenience. If a
//! change here is intended, it is a change in payout behaviour and needs a
//! written justification.
//!
//! # Provenance of the fixture
//!
//! ## `E`, `F`, `D`, `P` -- captured from the pre-refactor engine (unchanged)
//!
//! The generator was a throwaway host binary that `include!`d the ORIGINAL code
//! rather than a retyped copy of it, so nothing could drift in transcription:
//!
//! ```text
//! git show ceacc37:src/table_canister/src/lib.rs > orig_lib.rs
//!
//! # Assemble a generator module from orig_lib.rs. Two textual edits only:
//! #   * derive lists lose `CandidType, Deserialize, `  (no candid dep needed)
//! #   * `ic_cdk::println!` becomes a macro that pushes into a Vec<String>
//! # plus minimal stand-ins for the three TableState fields calculate_side_pots
//! # touches (players: Vec<Option<Player>>, side_pots, pot).
//! # `include!` it into main.rs so the private `fn`s stay reachable -- NO
//! # visibility edits.
//!
//! cargo run --release > golden_vectors.txt
//! ```
//!
//! ## `S` -- REGENERATED 2026-08-04, on wasm32, and here is why
//!
//! The original `S` lines were generated by running that host binary, i.e.
//! NATIVELY. `shuffle_deck` reduced a `u64` draw with
//! `(random_value as usize) % (i + 1)`, and `usize` is 32 bits on
//! `wasm32-unknown-unknown`, so the shuffle the canister actually performed was
//! NOT the shuffle those vectors pinned. All 2,000 of them encoded a deck order
//! that had never been dealt on-chain, and no third party could reproduce a real
//! deal from the revealed seed. See `docs/FINDING-02-shuffle-not-verifiable.md`.
//!
//! `shuffle_deck` is now width-independent and rejection-sampled
//! (`docs/SHUFFLE-SPEC.md`), and the `S` lines were regenerated by executing the
//! new shuffle **inside a wasm32-unknown-unknown module**, over the same 2,000
//! seeds, via:
//!
//! ```text
//! cargo test -p poker_core --test wasm32_golden -- --nocapture   # verifies
//! CLEARDECK_REGENERATE_SHUFFLE_VECTORS=1 \
//!   cargo test -p poker_core --test wasm32_golden -- --nocapture # rewrites S lines
//! ```
//!
//! Nobody had ever played on mainnet, so no deck history was invalidated by the
//! change. If a future change makes the two targets disagree again, the wasm32
//! target is the one that is right.

mod common;

use common::golden::{
    run_all, Counts, ALPHA, EXPECTED_FIVE_CARD, EXPECTED_SEVEN_CARD, EXPECTED_SHUFFLE,
    EXPECTED_SIDE_POTS, EXPECTED_STRAIGHT, GOLDEN,
};
use poker_core::create_deck;

#[test]
fn golden_vectors_reproduce_the_pinned_engine() {
    let outcome = run_all(GOLDEN);
    if let Err(report) = outcome.verify() {
        panic!(
            "golden vectors diverged on the HOST target ({} of {} vectors failed):\n{}",
            outcome.failures.len(),
            outcome.counts.shuffle
                + outcome.counts.seven_card
                + outcome.counts.five_card
                + outcome.counts.straight
                + outcome.counts.side_pots,
            report
        );
    }
    // Guard against a truncated or silently-emptied fixture.
    assert_eq!(
        outcome.counts,
        Counts {
            shuffle: EXPECTED_SHUFFLE,
            seven_card: EXPECTED_SEVEN_CARD,
            five_card: EXPECTED_FIVE_CARD,
            straight: EXPECTED_STRAIGHT,
            side_pots: EXPECTED_SIDE_POTS,
        }
    );
}

#[test]
fn create_deck_order_is_pinned() {
    // The pre-shuffle deck order is an input to the provably-fair shuffle, so it
    // is part of the fairness commitment: reordering it silently changes which
    // cards a given revealed seed deals. Every symbol, in order.
    assert_eq!(
        common::golden::deck_order_symbols(),
        std::str::from_utf8(ALPHA).unwrap(),
        "create_deck() no longer yields Hearts,Diamonds,Clubs,Spades x Two..Ace in order"
    );
    assert_eq!(create_deck().len(), 52);
}

#[test]
fn golden_side_pot_vectors_exercise_the_capping_branch() {
    // The f64 proportional-capping branch is the most dangerous code in the
    // side-pot routine, so assert the fixture really reaches it.
    let capped = GOLDEN
        .lines()
        .filter(|l| l.starts_with("P ") && l.contains("BUG: Side pots"))
        .count();
    assert!(
        capped >= 100,
        "golden fixture only reaches the capping branch {} times; it must stay covered",
        capped
    );
}

/// The `S` family is the fairness commitment, so its seeds must stay varied: a
/// fixture of 2,000 identical-length seeds would not exercise the variable-length
/// first link of the hash chain.
#[test]
fn shuffle_vector_seeds_are_varied() {
    let mut lengths: Vec<usize> = GOLDEN
        .lines()
        .filter(|l| l.starts_with("S "))
        .map(|l| l[2..].split(' ').next().expect("seed").len() / 2)
        .collect();
    assert_eq!(lengths.len(), EXPECTED_SHUFFLE);
    lengths.sort_unstable();
    lengths.dedup();
    assert!(
        lengths.len() >= 8,
        "only {} distinct seed lengths in the shuffle vectors",
        lengths.len()
    );
    assert!(
        *lengths.first().unwrap() >= 1 && *lengths.last().unwrap() >= 32,
        "seed lengths {:?} should span short seeds through a full 32-byte IC seed",
        lengths
    );
}
